DELETE http://localhost:3003/api/blogs/6530ee8506a52c261b11753b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxpaXN1a2thMSIsImlkIjoiNjUzMDE4NmIzNDRiZWNlNWVmNDhhYTkyIiwiaWF0IjoxNjk3NzAzMTA2LCJleHAiOjE2OTc3MDY3MDZ9.WSfEgditCIEI_dbdir8SSO-DzqIB2GYa2aHV488uL8U
