# fly.toml app configuration file generated for empty-leaf-9588 on 2023-10-11T15:33:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-leaf-9588"
primary_region = "arn"

[build]

[env]
	PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
